[project]
name = "fireblocks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "compass-api-sdk>=1.1.0",
    "devtools>=0.12.2",
    "dotenv>=0.9.9",
    "web3>=7.13.0",
    "ruff>=0.11.6",
    "pyperclip>=1.9.0",
]
