name: Run Smart Accounts

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  run-zero-dev:
    runs-on: ubuntu-latest
    env:
      COMPASS_API_KEY: ${{ secrets.COMPASS_API_KEY }}
      PRIVATE_KEY:  ${{ secrets.PRIVATE_KEY }}
      ZERODEV_RPC:  ${{ secrets.ZERODEV_RPC }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Change directory
      run: cd smart_accounts
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: PWD
      working-directory: smart_accounts/zerodev
      run: pwd
    
    - name: Install dependencies
      working-directory: smart_accounts/zerodev
      run: npm install
    
    - name: Run application
      working-directory: smart_accounts/zerodev
      run: npm run start

  run-safe:
    runs-on: ubuntu-latest
    env:
      COMPASS_API_KEY: ${{ secrets.COMPASS_API_KEY }}
      SIGNER_ADDRESS: "0xb8340945eBc917D2Aa0368a5e4E79C849c461511"
      SIGNER_PRIVATE_KEY: ${{ secrets.SIGNER_PRIVATE_KEY }}
      ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}
      SAFE_ADDRESS: "0xd6C05083ebA87Cef07652f81b0c836c500c2db92"
      SAFE_TX_SERVICE_URL: "https://safe-transaction-arbitrum.safe.global"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Change directory
      run: cd smart_accounts

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: PWD
      working-directory: smart_accounts/safe
      run: pwd

    - name: Install dependencies
      working-directory: smart_accounts/safe
      run: npm install

    - name: Run application
      working-directory: smart_accounts/safe
      run: npm run start
