name: Run Smart Accounts

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  run-zero-dev:
    runs-on: ubuntu-latest
    env:
      COMPASS_API_KEY: ${{ secrets.COMPASS_API_KEY }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Change directory
      run: cd smart_accounts
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: PWD
      working-directory: smart_accounts/zerodev
      run: pwd
    
    - name: Install dependencies
      working-directory: smart_accounts/zerodev
      run: npm install
    
    - name: Run application
      working-directory: smart_accounts/zerodev
      run: npm run start

  run-safe:
    runs-on: ubuntu-latest
    env:
      COMPASS_API_KEY: ${{ secrets.COMPASS_API_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Change directory
      run: cd smart_accounts

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: PWD
      working-directory: smart_accounts/safe
      run: pwd

    - name: Install dependencies
      working-directory: smart_accounts/safe
      run: npm install

    - name: Run application
      working-directory: smart_accounts/safe
      run: npm run start
