name: Minimal matrix demo

on:
  workflow_dispatch:

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      items: ${{ steps.set-output.outputs.items }}
    steps:
      - id: set-output
        run: |
          echo 'items={"item":["foo","bar"]}' >> $GITHUB_OUTPUT

  echo-item:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.discover.outputs.items) }}
    steps:
      - run: echo "Hello from ${{ matrix.item }}"