name: test_usecases_v_one

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  # Allow manual triggering
  push:
    branches:
      - main
  workflow_dispatch:

jobs:


  run-basic-examples:
    runs-on: ubuntu-latest
    env:
      COMPASS_API_KEY: ${{ secrets.COMPASS_API_KEY }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ZERODEV_RPC: ${{ secrets.ZERODEV_RPC }}
      WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh


      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          cache: false


      - name: Anvil Fork Base
        run: |
          anvil \
          --block-time 0.05 \
          --hardfork prague \
          --host 0.0.0.0 \
          --fork-url ${{ secrets.FORK_BASE_RPC_URL }} \
          --port 8546 \
          --chain-id 8453 \
          --no-rate-limit &
          sleep 5

      - name: Install dependencies
        working-directory: v1/basic_examples/deposit_on_aave/python_example
        run:
          uv sync

      - name: Run example
        working-directory: v1/basic_examples/deposit_on_aave/python_example
        run:
          ./.venv/bin/python main.py

  failure-alert:
    if: failure() && github.event_name == 'schedule' # Runs only if a previous job failed & triggered by cron
    runs-on: ubuntu-latest
    needs: [run-basic-examples]
    steps:
      - name: Send failure notification
        run: |
          curl -X POST "https://allquiet.app/api/webhook/829f846c-4dfa-4a58-ab33-eafae34a57c9" \
              -H "Content-Type: application/json" \
              -d '{"status": "Open", "severity": "Critical", "message": "GitHub workflow failed", "run_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
