name: test_python_sdk_snippets

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  discover_sdk_snippets:
    runs-on: ubuntu-latest
    env:
      COMPASS_API_KEY: ${{ secrets.COMPASS_API_KEY }}

    outputs:
      items: ${{ steps.collect.outputs.items }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv and Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (uv)
        working-directory: v1/test_sdk_snippets
        run: uv sync

      - id: collect
        name: Collect endpoints (writes items=... to $GITHUB_OUTPUT)
        working-directory: v1/test_sdk_snippets
        run: uv run python discover_endpoints.py