name: workflow 1

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      items: ${{ steps.collect.outputs.items }}   # <-- expose "items"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - id: collect
        run: |
          python - <<'PY'
          import json, os
          # Pretend we "discovered" 3 items
          values = ["x", "y", "z"]
          matrix = {"item": values}
          print("Discovered:", matrix)

          # Write to GitHub Actions output file
          with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
            fh.write(f"items={json.dumps(matrix)}\n")
          PY
      - name: Echo raw output (debug)
        run: echo "items = ${{ steps.collect.outputs.items }}"

  echo-item:
    needs: discover
    # Only run if discover produced something JSON-ish
    if: ${{ needs.discover.outputs.items != '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # Fallback to an empty matrix if items is blank (prevents fromJson('') errors)
      matrix: ${{ fromJson(needs.discover.outputs.items != '' && needs.discover.outputs.items || '{"item":[]}' ) }}
    steps:
      - run: echo "Hello from ${{ matrix.item }}"