name: Smoke test code samples (parallel)



on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  pull_request:
     branches:
       - main
  workflow_dispatch:

#on:
#  workflow_dispatch: {}
#  push:
#    paths:
#      - ".github/workflows/smoke-spec.yml"

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.collect.outputs.paths }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Collect endpoints from spec (minus BROKEN)
        id: collect
        env:
          API_URL: "https://spec.speakeasy.com/compasslabs/api/compass-api-with-code-samples"
        run: |
          python - <<'PY'
          import json, os, requests, sys
          API_URL = os.environ["API_URL"]
          print("✅ Able to import requests and reach", API_URL)
          PY