name: test_v1_tutorials

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  # Allow manual triggering
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  run-pendle:
    runs-on: ubuntu-latest
    env:
      COMPASS_API_KEY: ${{ secrets.COMPASS_API_KEY }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}
      SERVER_URL: http://localhost:8000
      PENDLE_API_URL: https://api-v2.pendle.finance
      MORPHO_GRAPHQL_API_URL: https://blue-api.morpho.org/graphql
      THE_GRAPH_URL_AAVE_ARBITRUM: https://gateway.thegraph.com/api/subgraphs/id/DLu
      THE_GRAPH_URL_AAVE_ETHEREUM: https://gateway.thegraph.com/api/subgraphs/id/Cd2gED
      THE_GRAPH_URL_AAVE_BASE: https://gateway.thegraph.com/api/subgraphs/id/GQFb
      THE_GRAPH_API_KEY: 815da
      ENV: "production"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: PWD
        working-directory: v1/pendle/typescript
        run: pwd




      - name: Start up full local API and anvil
        uses: ./.github/actions/local_anvil_and_api
        with:
          ethereum_rpc_url: ${{ secrets.ETHEREUM_MAINNET_RPC_URL }}
          arbitrum_rpc_url: ${{ secrets.ARBITRUM_MAINNET_RPC_URL }}
          base_rpc_url: ${{ secrets.BASE_MAINNET_RPC_URL }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          mono_app_id: ${{ secrets.MONOREPOAPP_ID }}
          mono_app_private_key: ${{ secrets.MONOREPOAPP_PRIVATE_KEY }}
          fund_amount_eth: "10"




      - name: Install dependencies
        working-directory: v1/pendle/typescript
        run: npm install

      - name: Build application
        working-directory: v1/pendle/typescript
        run: npm run build

      - name: Run application
        working-directory: v1/pendle/typescript
        env:
          RPC_URL: ${{ steps.anvil.outputs.arbitrum_local_url }}
        run: npm run start

  failure_alert:
    if: failure() && github.event_name == 'schedule'
    runs-on: ubuntu-latest
    needs: [run-pendle]
    steps:
      - name: Send failure notification
        run: |
          curl -X POST "https://allquiet.app/api/webhook/829f846c-4dfa-4a58-ab33-eafae34a57c9" \
               -H "Content-Type: application/json" \
               -d '{"status": "Open", "severity": "Critical", "message": "GitHub workflow failed", "run_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
