name: workflow 1

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      items: ${{ steps.collect.outputs.items }}   # <-- expose "items"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - id: collect
        run: python v1/test_sdk_snippets/discover_endpoints.py   # <-- run script
      - run: echo "items = ${{ steps.collect.outputs.items }}"

  echo-item:
    needs: discover
    if: ${{ needs.discover.outputs.items != '' }}
    runs-on: ubuntu-latest

    env:
      COMPASS_API_KEY: ${{ secrets.COMPASS_API_KEY }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ARBITRUM_RPC_URL: http://localhost:8547
      SERVER_URL: http://localhost:80
      NPM_PACKAGE_VERSION: ${{ needs.set-versions.outputs.npm_package_version }}
      UV_PACKAGE_VERSION: ${{ needs.set-versions.outputs.uv_package_version }}

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.discover.outputs.items) }}
    steps:
      - uses: actions/checkout@v4          # <-- required in every job
      - uses: actions/setup-python@v5      # <-- fresh VM, set up Python again
        with:
          python-version: "3.11"
      - name: Install Python deps          # <-- if your script needs them
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv
      - run: python v1/test_sdk_snippets/run_endpoint.py
        env:
          ENDPOINT: ${{ matrix.item }}